### ISSUE TITLE
OG image broken with switch to default prerendering mode

### ISSUE THREAD

**Issue by danirukun** [watsonindustries/hololivefanbooth#8]
SvelteKit has a prerender mode, which allows to save on client rendering.
However, this seemed to break the URLs to the OG images: https://www.opengraph.xyz/url/https%3A%2F%2Fwww.hololivefanbooth.com

The solution is somewhere here: https://github.com/watsonindustries/hololivefanbooth/blob/main/src/routes/%2Blayout.svelte#L25

Don't forget about the secure image url too.

**Comment by CenTdemeern1** [comment]
Can't reproduce, works fine for me
![Screenshot 2023-06-12 at 16 58 55](https://github.com/watsonindustries/hololivefanbooth/assets/24682280/f6ad0b27-a3aa-49a3-b227-f7f6be5d75ed)

**Comment by CenTdemeern1** [comment]
Whoops, didn't run correctly, issue is reproducible. My bad.

**Comment by CenTdemeern1** [comment]
![IMG_4550](https://github.com/watsonindustries/hololivefanbooth/assets/24682280/c0611e8b-ee2f-447f-8e8b-46576ef8dc47)
